# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cost_calculation_ <- function(A_, B_, p) {
    .Call('_approxOT_cost_calculation_', PACKAGE = 'approxOT', A_, B_, p)
}

multi_marg_final_cost_ <- function(idx_, data_, mass_, M, D, p, ground_p) {
    .Call('_approxOT_multi_marg_final_cost_', PACKAGE = 'approxOT', idx_, data_, mass_, M, D, p, ground_p)
}

multi_marg_given_dist_ <- function(idx_, mass_, cost_, M, N_cost, p) {
    .Call('_approxOT_multi_marg_given_dist_', PACKAGE = 'approxOT', idx_, mass_, cost_, M, N_cost, p)
}

#' Returns orders along the Hilbert space-filling Curve
#'
#' @param A a matrix of data-values of class Eigen::MatrixXd
#' @return An integer vector of orders
#' @keywords internal
hilbert_proj_ <- function(A) {
    .Call('_approxOT_hilbert_proj_', PACKAGE = 'approxOT', A)
}

sinkhorn_ <- function(p_, q_, cost_matrix_, epsilon, niterations) {
    .Call('_approxOT_sinkhorn_', PACKAGE = 'approxOT', p_, q_, cost_matrix_, epsilon, niterations)
}

sinkhorn_pot_ <- function(mass_a, mass_b, cost_matrix, epsilon, niterations, unbiased, cost_matrix_A, cost_matrix_B) {
    .Call('_approxOT_sinkhorn_pot_', PACKAGE = 'approxOT', mass_a, mass_b, cost_matrix, epsilon, niterations, unbiased, cost_matrix_A, cost_matrix_B)
}

transport_C_ <- function(mass_a_, mass_b_, cost_matrix_, method_, epsilon_, niter_, unbiased_, threads_, cost_matrix_A_, cost_matrix_B_) {
    .Call('_approxOT_transport_C_', PACKAGE = 'approxOT', mass_a_, mass_b_, cost_matrix_, method_, epsilon_, niter_, unbiased_, threads_, cost_matrix_A_, cost_matrix_B_)
}

transport_ <- function(A_, B_, p, ground_p, method_, a_sort, epsilon_ = 0.0, niter_ = 0L, unbiased_ = FALSE, threads_ = 1L) {
    .Call('_approxOT_transport_', PACKAGE = 'approxOT', A_, B_, p, ground_p, method_, a_sort, epsilon_, niter_, unbiased_, threads_)
}

transport_swap_ <- function(A_, B_, idx_, mass_, p, ground_p, tolerance_, niter_ = 0L) {
    .Call('_approxOT_transport_swap_', PACKAGE = 'approxOT', A_, B_, idx_, mass_, p, ground_p, tolerance_, niter_)
}

wasserstein_ <- function(mass_, cost_, p, from_, to_) {
    .Call('_approxOT_wasserstein_', PACKAGE = 'approxOT', mass_, cost_, p, from_, to_)
}

wasserstein_p_iid_ <- function(X_, Y_, p) {
    .Call('_approxOT_wasserstein_p_iid_', PACKAGE = 'approxOT', X_, Y_, p)
}

wasserstein_p_iid_p_ <- function(X_, Y_, p) {
    .Call('_approxOT_wasserstein_p_iid_p_', PACKAGE = 'approxOT', X_, Y_, p)
}

